M48
; DRILL file {KiCad 7.0.1} date Sat Apr 29 04:40:29 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-29T04:40:29+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X108.319Y-48.372
X113.169Y-48.372
T2
X108.019Y-45.342
X113.469Y-45.342
T0
M30
